### ISSUE TITLE
HTTP messages should use CRLF as the line separator

### ISSUE THREAD

**Issue by dvlato** [HotelsDotCom/styx#103]
## The problem
HTTP messages should use CRLF as the end of line marker. 

## Detailed description
According to the HTTP spec,  the CRLF sequence must be used as the line separator in all parts of a HTTP message  except for the entity body. The entity body for "text types" is allowed to have CRLF, LF or CR, but the canonical form also has CRLF as a separator and it's the recommended one.
The safest and most cohesive approach for HTTP messages generated in STYX seems to be codifying the new line marker as CRLF in all the cases.

Relevant parts of the spec:

HTTP/1.1 defines the sequence CR LF as the end-of-line marker for all
   protocol elements except the entity-body (see appendix 19.3 for
   tolerant applications). The end-of-line marker within an entity-body
   is defined by its associated media type, as described in section 3.7.

from RFC2616 https://tools.ietf.org/html/rfc2616#section-2.2

MIME's canonical form requires that media subtypes of the "text" type
   use CRLF as the text line break.  HTTP allows the transfer of text
   media with plain CR or LF alone representing a line break, when such
   line breaks are consistent for an entire representation.  An HTTP
   sender MAY generate, and a recipient MUST be able to parse, line
   breaks in text media that consist of CRLF, bare CR, or bare LF.  In
   addition, text media in HTTP is not limited to charsets that use
   octets 13 and 10 for CR and LF, respectively.  This flexibility
   regarding line breaks applies only to text within a representation
   that has been assigned a "text" media type; it does not apply to
   "multipart" types or HTTP elements outside the payload body (e.g.,
   header fields).

from RFC 7231 https://tools.ietf.org/html/rfc7231#section-3.1.1.3

**Comment by mikkokar** [comment]
Hi @dvlato can you

- provide a specific example or use case that demonstrates this issue?
- also describe what is the particular issue this is causing, as in "a test case *NNN* fails on Windows"?

I am curious about the impact of this because Styx *doesn't do* any HTTP framing itself. All of this happens via Netty. It would be rather surprising if Netty was not following the HTTP spec. But even if they were not, it wouldn't probably matter due to the popularity of the project.

**Comment by dvlato** [comment]
After reviewing this, we are adding LF characters after the body of our messages in a few different points: 
 -PluginToggleHandler
 -StyxConfigurationHandler
-VersionTextHandler
-OriginsReloadCommandHandler

There are no LF characters used as line separators in any other parts of the message (headers, or bodies of mime/multipart)  and the LF after the body in those admin endpoints was requested for specific usages.   Changing the LF for a CRLF could break compatibility with tools that do not support CRLF. 

Since the current LFs are consistent for the entire text body and for compatibility reasons with automated tools, we can close this issue.
