### ISSUE TITLE
Licence header in incorrect format

### ISSUE THREAD

**Issue by kvosper** [HotelsDotCom/styx#107]
## The problem
When using the code formatter in IntelliJ IDEA (and possibly other IDEs), undesirable modifications are made to the licence header.

## Detailed description
The licence header in each source file is written as a Javadoc comment. As a result, when code-formatting IDE features are used, they often modify the header, e.g. adding HTML `<p>` tags. This in turn prevents the licence header plugin from recognising the existing header and causes it to add a new one on top.

The maven plugin used is `com.mycila.license-maven-plugin` which can be found in the root `pom.xml` file. Other relevant files are `src/license/header-definitions.xml` and `src/license/templates/APACHE-2.txt`.

## Acceptance criteria
* Licence header should not be modified by IntelliJ IDEA code formatter.

**Comment by dvlato** [comment]
Instructions to solve this: 
- Add the following "mapping" configuration to the mycila maven-license-plugin in the parent's pom.xml:
        _<configuration>
          <header>file:///${main.basedir}/src/license/templates/APACHE-2.txt</header>_
          **<mapping>
              <java>SLASHSTAR_STYLE</java>
              <scala>SLASHSTAR_STYLE</scala>
          </mapping>**

Run the license:format maven goal.

**Comment by kvosper** [comment]
Implemented in #131
