### ISSUE TITLE
Styx fails to start with the default configuration file

### ISSUE THREAD

**Issue by dvlato** [HotelsDotCom/styx#110]
## The problem
Version styx-0.7.5 does not start when using the "default.yml" bundled in the archive.

## Detailed description
Version of styx: styx-0.7.5 . This did not happen with the previous version styx-0.7.4
When trying to run styx as per the quick start guide:
```
<YOUR_INSTALL_DIR>/bin/startup
```
* That means that the process will use the default configuration file, so it is equivalent (and causes the same error) to this command:
 `<YOUR_INSTALL_DIR>/bin/startup <YOUR_INSTALL_DIR>/conf/default.yml`

The process fails to start with the following exception: 
```
11:08:05.919 [main] INFO  c.h.s.i.c.yaml.YamlConfig - Loading configuration from file: path=/styx/conf/default.yml
Mar 16, 2018 11:08:06 AM com.hotels.styx.infrastructure.logging.LOGBackConfigurer initLogging
INFO: Initializing LOGBack from [/styx/conf/logback.xml]. If you are watching the console output, it may stop after this point, if configured to only write to file.
WARN  2018-03-16 11:08:06 [c.h.s.StyxServer] [build=release.label_IS_UNDEFINED] [main] - Could not acquire build number from release version: Version{releaseTag=STYX.0.7-SNAPSHOT}
INFO  2018-03-16 11:08:06 [c.h.s.s.ServiceFactoriesConfig] [build=release.label_IS_UNDEFINED] [main] - Service 'backendServiceRegistry' is ENABLED
ERROR 2018-03-16 11:08:06 [c.h.s.StyxServer] [build=release.label_IS_UNDEFINED] [main] - Error in Styx instance creation.
[exceptionClass=com.hotels.styx.serviceproviders.ServiceFactoryConfig, exceptionMethod=loadService, exceptionID=1efa334c]
com.hotels.styx.api.configuration.ConfigurationException: Error creating service
	at com.hotels.styx.serviceproviders.ServiceFactoryConfig.loadService(ServiceFactoryConfig.java:91) ~[styx-proxy-0.7-SNAPSHOT.jar:na]
.......	
Caused by: com.hotels.styx.api.configuration.ConfigurationException: empty [services.registry.factory.config.originsFile] config value for factory class FileBackedBackendServicesRegistry.Factory
	at com.hotels.styx.proxy.backends.file.FileBackedBackendServicesRegistry$Factory.requireNonEmpty(FileBackedBackendServicesRegistry.java:172) ~[styx-proxy-0.7-SNAPSHOT.jar:na]
	at java.util.Optional.map(Optional.java:215) ~[na:1.8.0_60]

````
## Acceptance criteria

Styx should start up successfully when using the default yaml config file.

**Comment by kvosper** [comment]
I would not have expected previous versions to work like that either. We have completed files like [env-development/styx-config.yml](https://github.com/HotelsDotCom/styx/blob/master/distribution/conf/env-development/styx-config.yml) for starting up Styx.

This may change around the use of config files in the future, but for the time being, this is expected behaviour.

**Comment by kvosper** [comment]
It looks like we have `/bin/startup` referring to `default.yml`, but that file does not supply sufficient configuration to start-up.

**Comment by mikkokar** [comment]
Could you @dvlato just add a simplistic origins file for the default configuration and push a fix?

**Comment by mikkokar** [comment]
PR:  #111.
