### ISSUE TITLE
Remove fasterxml objects from the BackendService etc. classes

### ISSUE THREAD

**Issue by mikkokar** [HotelsDotCom/styx#132]
## The problem
The BackendService API object exposes `com.fasterxml` annotations:

```
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder;
```

Remove them from the interface.

## Detailed description
The yaml serialisation ought to move out of the API module. This can be implemented somewhere in styx-proxy module. We can use an intermediate form, perhaps a java bean based, to perform deserialisation (from yaml configuration) and serialisation (to admin interface).

## Acceptance criteria
- The `com.fasterxml.*` imports no longer appear in BackendService & related API classes.
- The admin interface remains unaffected.

**Comment by kvosper** [comment]
A possible implementation is to replace the fasterxml annotations with new ones created inside the Styx codebase. This ought to make it easier to adapt to JSON (de)serialisation without needing to programmatically add every property into some translation layer.
