### ISSUE TITLE
Built-in generic plugin - feature request/discussion

### ISSUE THREAD

**Issue by kvosper** [HotelsDotCom/styx#157]
## The problem
Sometimes a plugin will be desired to do something very basic, such as adding some headers to the request or response with set values. It is not very efficient to create a whole new project/dependency for something so simple.

The following details are more of a concept than a finished feature request, and should be discussed and likely amended before implementation.

## Detailed description
It would be easier if there were a built-in `Plugin` (and `PluginFactory`) implementation that could be used to configure simple plugins without needing to write any new code.
Furthermore, this intrinsically allows us to minimise the impact of API changes on Plugin users.

## Acceptance criteria
* Allow plugin to be configured without writing code
* Only needs to support the addition of headers

**Comment by mikkokar** [comment]
Internal plugins should be enabled via Styx routing configuration. Please refer to the Styx user manual, advanced routing configuration for examples and further information.

**Comment by mikkokar** [comment]
Do you have more specific requirements for header addition? Such as:
- Are the headers added indiscriminately for all requests?
- Are the header added based on some condition?
