### ISSUE TITLE
Restrict health checks by time since response

### ISSUE THREAD

**Issue by kvosper** [HotelsDotCom/styx#161]
## The problem
The scheduled health-checks in Styx are performed periodically in Styx, however, if we are receiving valid responses from an origin, we already know that the origin is healthy, so we don't really need to health-check it.

## Detailed description
We know that an origin is healthy if it is sending back valid responses, so we do not need to perform an additional health-check unless the time since the last response has been longer than our health-check interval.

There may be some unusual use cases in which this logic does not apply, so we could add an opt-in feature to force explicit health-checks.

## Acceptance criteria
* Only perform health-check if the time elapsed since the last valid response exceeds the health-check interval.
* Provide an optional feature, disabled by default, that forces health-checks to be performed regardless of responses.

**Comment by mikkokar** [comment]
This is a massive assumption. Application's health check API could use built-in logic to determine its own status that cannot be inferred from in-flight HTTP requests. Also the application health checks can be used to signal an administrative shutdown of the app.

Therefore won't do.
