### ISSUE TITLE
Add admin endpoint for querying specific metrics

### ISSUE THREAD

**Issue by kvosper** [HotelsDotCom/styx#182]
## The problem
We currently have an endpoint that returns the entire set of metrics, but it may be useful to have an endpoint that when queried can return an arbitrary metric specified in the HTTP request. This could allow more sophisticated health-checking options for those that need it.

## Detailed description
The URL pattern will be `/admin/metrics/<METRIC_NAME_OR_PREFIX>`, so if the URL was:
`/admin/metrics/foo.bar`
it would return a metric named `foo.bar` as well as metrics beginning with this prefix such as `foo.bar.baz`.

These can be returned as a JSON object by simply filtering the map of metrics for those that match the pattern and converting it to JSON.

If the metric does not exist it can return 404.

## Acceptance criteria
* Add an admin endpoint that allows the user to drill down to a specific metric
* Returns metric matching exact name if it exists
* Returns metric whose name has specified prefix
* If no metrics are found, returns 404

**Comment by mikkokar** [comment]
Cherry picked to `styx-1.0-dev` by #218 .
