### ISSUE TITLE
Refactor OriginsInventory, BackendServiceRouter for Styx 1.0

### ISSUE THREAD

**Issue by kvosper** [HotelsDotCom/styx#197]
## The problem
`OriginsInventory` is class that couples too many responsibilities in one place. 

A consequence of this is that when the `BackendServiceRouter` is informed of changes to the back-end services, it entirely recreates the `OriginsInventory` for the modified service(s).

Creating and destroying these objects at runtime can cause further issues, as `OriginsInventory` is responsible for consuming and publishing events. 

The risk is that an old `OriginsInventory` will publish an outdated snapshot after the new `OriginsInventory`, thus misinforming subscribers.

"Quick & dirty" solutions only introduce other problems (like having a gap in which no `OriginsInventory` exists to handle events).

We must refactor our code to both reduce complexity and prevent bugs.

## Detailed description
We can use Styx 1.0's `ConfigStore` class to help us with the decoupling, by storing our back-end service config in there and allowing various other classes to watch it for change events.

For example a class to start and stop origins monitoring could watch the `ConfigStore` and then the monitors could publish the results of their health checks back to the `ConfigStore`.

## Acceptance criteria
* Eliminate the risk of multiple conflicting "sources of truth" regarding origins
* Decouple the various responsibilities of `OriginsInventory`
* Simplify the behaviour executed when back-end services are reconfigured

**Comment by mikkokar** [comment]
Won't do. These classes will be deprecated by the routing object model.
