### ISSUE TITLE
Origin metrics for request cancellations count all requests

### ISSUE THREAD

**Issue by kvosper** [HotelsDotCom/styx#199]
## The problem
The metric `<prefix>.origins.<origin-id>.requests.cancelled.count` counts all requests, not just cancelled requests.

## Detailed description
`StyxHttpClient` assumes that any unsubscription is a cancellation and updates the origin cancellation metrics accordingly.

In reality, RxJava calls `unsubscribe` whenever an observable terminates.

We need a way to allow `StyxHttpClient` to distinguish cancellations from other situations.

## Acceptance criteria
* Unsubscriptions that are part of the normal flow should not be recorded as cancellations
* Real cancellations should still be recorded

**Comment by mikkokar** [comment]
Merged to both `master` and `styx-1.0-dev`.
