### ISSUE TITLE
[1.0] Remove obsolete method from HttpRequest.Builder

### ISSUE THREAD

**Issue by kvosper** [HotelsDotCom/styx#200]
## The problem
`HttpRequest.Builder.body(String)` should be removed.

## Detailed description
`HttpRequest` is to be our streaming class, but this method sets a full body.

Original `TODO` from @mikkokar :
> This method is bad because it just takes string instead of stream of chunks. Also it implicitly assumes UTF_8 encoding.

It will also be necessary to update any code using it.

## Acceptance criteria
* Method is removed
* It is still possible to accomplish the same goal, if required
* Tests using this that should be using `FullHttpRequest` anyway updated

**Comment by mikkokar** [comment]
Fixed by PR #205
