### ISSUE TITLE
Memory leak in styx V 0.14.0

### ISSUE THREAD

**Issue by salahqasem** [HotelsDotCom/styx#222]
## The problem
We are facing a memory leak in Styx V-0.14.0.

## Detailed description
After investigation we found that the root cause of this issue is related to the dashboard each time we trigger the dashborad update event the code register new Origins objects to the google guava eventbus and it dose not unregister old objects see
com.hotels.styx.admin.dashboard.DashboardData$Backend constructer
with time this behavior fill the memory with unused objects that not eligible for the GC 

## Acceptance criteria
When trigger the dashboard update event before registering new origins to the eventbus, old Origins MUST unregistered.

**Comment by mikkokar** [comment]
@salahqasem A PR is pending. Feel free to have a look.

**Comment by salahqasem** [comment]
Thanks @mikkokar
