### ISSUE TITLE
Unused method `isHttps` in StyxHttpClient.

### ISSUE THREAD

**Issue by mikkokar** [HotelsDotCom/styx#235]
## The problem

StyxHttpClient has a unused public `isHttps` method. Removing the method allows us also to drop a dependency to `BackendService` class.

## Acceptance criteria

* There is no `isHttps` method in `StyxHttpClient`.
* `StyxHttpClient.Builder` no longer takes a `BackendService` as a constructor argument. It shall take an application ID instead.

**Comment by VivianLopes** [comment]
We cannot eliminate `BackendService` from `StyxHttpClient` just by deleting `StyxHttpClient.isHttps` as it is also used to get `stickySessionConfig()`.

**Comment by mikkokar** [comment]
Hi @VivianLopes, just pass in the SticySessionConfig instead of BackendService ;-).
