### ISSUE TITLE
Remove Announcer class

### ISSUE THREAD

**Issue by kvosper** [HotelsDotCom/styx#268]
## The problem
The class `com.hotels.styx.api.Announcer` seems redundant.

## Detailed description
`Announcer` holds a list of listeners and uses relatively complex logic (using `java.lang.reflect.Proxy`) to iterate through and call their listen methods.

 Specifically, it creates a proxy object implementing the same listener interface, and then when methods are called on that object, it propagates the call to all of the listeners in its list.

It appears that this could be just as easily accomplished by using the list of listeners directly and calling `forEach(...)` to execute the listen methods. This suggests that `Announcer` is totally unnecessary.

## Acceptance criteria
* Use simple alternative as suggested above
* Remove `Announcer` class

**Comment by dvlato** [comment]
Won't do.
