### ISSUE TITLE
connections.total-connections count can get negative

### ISSUE THREAD

**Issue by mikkokar** [HotelsDotCom/styx#351]
## The problem

Styx `connections.total-connections` count can get negative.

## Detailed description

Most likely culprit is the `channelRegistered` handler in  `ExcessConnectionRejector`.

    @Override
    public void channelRegistered(ChannelHandlerContext ctx) throws Exception {
        if (channelGroup.size() >= maxConnectionsCount) {
            LOGGER.warn("Max allowed connection  to server exceeded: current={} configured={}", channelGroup.size(), maxConnectionsCount);
            ctx.close();
            return;
        }
        channelGroup.add(ctx.channel());
        super.channelRegistered(ctx);
    }

I suspect calling `ctx.close()` from`channelRegistered` triggers a `channelInactive` event without corresponding `channelActive`. As a result, `ChannelStatisticsHandler` ends up seeing more channel inactive than channel active events, and the count may drift below zero.

## Acceptance criteria
* A rejected connection is neutral with respect to total-connections count.

**Comment by mikkokar** [comment]
Fyi @taer

**Comment by kvosper** [comment]
Merged #360
