### ISSUE TITLE
Add additional metrics for healthchecks

### ISSUE THREAD

**Issue by dvlato** [HotelsDotCom/styx#367]
## The problem
Right now, the only metric we expose for healthchecks is a Meter with the failures for each backend service: 
https://github.com/HotelsDotCom/styx/blob/fa11fa1cd9e8f95580bd900d3398da24260b51e8/docs/user-guide/metrics.md#client-side-metrics

Additional metrics such as connection open/closed,  successful healthchecks, origin taken out of/back into rotation, etc should be added for improved traceability.

**Comment by mikkokar** [comment]
Won't do.
