### ISSUE TITLE
Cleanly separate the documents metrics.md and metrics-reference.md

### ISSUE THREAD

**Issue by kvosper** [HotelsDotCom/styx#368]
## The problem
The purposes of the documents `metrics.md` and `metrics-reference.md` have become a little muddled. We are adding metrics in some places and not others and it's not clear which document to read.

## Detailed description
`metrics.md` should be describing how a user can get information from our metrics, whereas `metrics-reference.md` is supposed to be an exhaustive list giving a description of each metric.

As well as filling in any gaps in `metrics-reference.md`, we should try to avoid just dumping the names of every metric into `metrics.md`, instead we should simply say which prefix to look under for particular categories of information and then point readers to `metrics-reference.md` for more details.

## Acceptance criteria
* Add any missing metrics to `metrics-reference.md`
* Avoid describing exact metrics in `metrics.md` (exceptions can be made if it is necessary to illustrate an example, but we should avoid overdoing it)

**Comment by mikkokar** [comment]
Action point: Dump all metrics and update the metrics reference accordingly.

**Comment by mikkokar** [comment]
Fixed by #469
