### ISSUE TITLE
Can dependency between server and client can be removed

### ISSUE THREAD

**Issue by bestokes** [HotelsDotCom/styx#375]
## Background
Currently styx-server depends on styx-client as a maven dependency. There are only few exception classes being used by styx-server, so maybe there is an opportunity there to reduce dependance.

## Acceptance criteria
* Check if the dependency can be removed,
* Propose a solution how to handle the exception classes used by styx-server from styx-client module,
* Remove the dependency if feasable.

---

One suggestion is to:

> Add an interceptor to map client specific exceptions to common styx exceptions.
> Remove the client specific exception mapping from the Styx HTTP Pipeline, and map styx common exceptions to specific response codes.
> Then we can remove the dependency between Styx Server and Client.
> However, as HttpPipelineHandler is part of Styx-Server, still needs to know about proxy related response codes, such as Gateway Timeout, etc. But then again HttpPipelineHandler already performs proxying related such as flow control.

> Ideally though HttpPipelineHandler as a server component would not have any proxying related logging in it. Instead the proxying related logic would all go to styx-proxy alone. Perhaps we should explore this split bit further?

**Comment by mikkokar** [comment]
Low value, let's do later if necessary.
