### ISSUE TITLE
Replace ugly code for testing in HttpPipelineHandler

### ISSUE THREAD

**Issue by bestokes** [HotelsDotCom/styx#376]
Regarding `buildForIoExceptionTest()` in `HttpPipelineHandler.Builder`

https://github.com/HotelsDotCom/styx/blob/master/components/server/src/main/java/com/hotels/styx/server/netty/connectors/HttpPipelineHandler.java#L731

> Look into `FlowControllingHttpContentProducer` and the corresponding `HttpResponsePropagator` classes. There the state machine (Flow Controlling Producer) has been isolated from the event source (`HttpResponsePropagator`), making it very easy to verify the state machine logic without having to resort to low level Netty mocking.

**Comment by mikkokar** [comment]
Will probably end up sitting in the queue forever until gets outdated. Therefore closing.
