### ISSUE TITLE
Race condition in ConfigStore

### ISSUE THREAD

**Issue by kvosper** [HotelsDotCom/styx#382]
## The problem
There seems to be a race condition in the method `watch(String, Class<T>)` in the class `com.hotels.styx.configstore.ConfigStore`.

## Detailed description
While running unit tests, some of the tests would not give consistent results - sometimes the test would pass, sometimes fail. Further investigation showed that an event was never being delivered.

The code was:
```
            components.environment().configStore().watch("loading.plugins", Object.class)
                    .toBlocking()
                    .first();
```
This code blocked indefinitely even though the value `loading.plugins` had been set.

Note: it was called from `ProxyServerSetUp.createProxyServer` and has been replaced by a workaround that uses polling.

## Acceptance criteria
(/) The race condition should no longer exist

**Comment by mikkokar** [comment]
Config store is going to go away.
