### ISSUE TITLE
Unused properties in Server config

### ISSUE THREAD

**Issue by kvosper** [HotelsDotCom/styx#428]
## The problem
Several properties exist in the `NettyServerConfig` that are not used anywhere. These could be deprecated, or the configurability may have been accidentally removed.

## Detailed description
These ones are not used:
* `tcpNoDelay`
* `nioReuseAddress`
* `nioKeepAlive`
* `maxContentLength`

## Acceptance criteria
* Reintroduce configurability where needed
* Remove any properties not needed

**Comment by manishsahni2000** [comment]
Hi ,

Can you please assign this on me ?

**Comment by manishsahni2000** [comment]
Hi ,

Can you please assign this on me

**Comment by mikkokar** [comment]
Thank you @manishsahni2000! I will have a look.

**Comment by mikkokar** [comment]
PR is #464.

**Comment by mikkokar** [comment]
Fixed & merged.
