### ISSUE TITLE
Path is not correct in docs/developer-guide.md

### ISSUE THREAD

**Issue by akumariiit** [HotelsDotCom/styx#461]
In file docs/developer-guide.md
Point 1.4 it says to start local server, run below command
```

$ ./styx-test/bin/startup
Running Styx startup...
...
/plenty of output/
...    
```

Path should be 
`$ ./styx-test/styx/bin/startup`

**Comment by mikkokar** [comment]
Thank you @akumariiit for reporting this. I will fix it.

**Comment by mikkokar** [comment]
FYI @akumariiit opened a PR to fix this: #462.

**Comment by mikkokar** [comment]
Fixed.

**Comment by akumariiit** [comment]
Thanks for fixing this 👍
