### ISSUE TITLE
Newly added HostProxy objects are not marked as inactive 

### ISSUE THREAD

**Issue by mikkokar** [HotelsDotCom/styx#495]
## Description

The newly added HostProxy objects, representing origins, are not marked as `inactive` in backwards compatibility mode (PR #458). Therefore, Styx LoadBalancingGroup momentarily sends traffic to them until a health checking service marks them as inactive.

## Background

When health checking is enabled, styx confirms that all newly added origins are healthy before adding them to the load balancing group. This is to prevent from accidental loss of data when a newly added origin is unresponsive.

## Acceptance Criteria

* When health checking is enabled
  * All HostProxy objects are inserted with `state:inactive` tag. This prevents LoadBalancingGroup from picking them up.
  * The health checking service will mark them with `state:active` after a successful health has been confirmed, subject to configuration and threshold values.

* When health checking is disabled
  * All HostProxy objects can be inserted untagged (without `state:inactive` tag). It is up for discussion if they should be inserted with `state:active` instead.

**Comment by OwenLindsell** [comment]
Fixed
