### ISSUE TITLE
Expose Styx origins configuration file content in backwards compatibility mode

### ISSUE THREAD

**Issue by mikkokar** [HotelsDotCom/styx#496]
The origins configuration (file content) is not exposed via the admin interface in the backwards compatibility mode (PR #458).

The contents are logged when the file is reloaded, but it would be better expose the actual configuration via the admin interface.

The file content should be exposed via this admin interface endpoint: `/admin/configuration/origins`

**Comment by chrisgresty** [comment]
Addressed with PR #520
