### ISSUE TITLE
Remove old admin endpoints when routing object forwarding is enabled

### ISSUE THREAD

**Issue by mikkokar** [HotelsDotCom/styx#497]
The following admin interface handlers are specific to the old application router only, and no longer supported in the routing object based traffic forwarding, or in the backwards compatibility mode (PR #458).

- /admin/dashboard/data.json
- /admin/dashboard/
- /admin/tasks/origins/reload
- /admin/tasks/origins/status
- /admin/tasks/origins

Acceptance criteria:

* These admin interface endpoints are visible when Styx is using the old application router.
* These admin interface endpoints are not available in when the routing object based forwarding is used.
* The relevant admin interface links (`indexLinkPaths` method in `AdminServerBuilder`) are not added when the routing object based forwarding is used.

**Comment by mikkokar** [comment]
Will be part of PR #503.

**Comment by bestokes** [comment]
Fixed in PR #503
