### ISSUE TITLE
Add support for BackendServiceProxy routing object

### ISSUE THREAD

**Issue by Kumar001** [HotelsDotCom/styx#519]
Add support for `BackendServiceProxy` routing object.

Use case: The deployment contains few different origins files. One per environment. A `BackendServiceProxy` object sources its configuration from a nominated origins file. 

The deployment has HTTP header based routing rules that decide which environment (ie what `BackendServiceProxy`) the traffic is sent to.

**Comment by mikkokar** [comment]
We have deprecated the `BackendServiceProxy` object. It uses the old monolithic routing engine. We are hoping to delete that monolithic code altogether in favour of the nimble and flexible routing object model.

However, the old origins file format is still supported with the "backwards compatibility mode" https://github.com/HotelsDotCom/styx/pull/458. This feature converts the origins file into a group of routing objects. 

As per #458 it is possible to configure several `YamlFileConfigurationService` providers. One for each origins file. They would each manage a separate set of routing objects:

- A `PathPrefixRouter` for each origins file.
- A `LoadBalancingGroup` for each backend service.
- A `HostProxy` for each origin.

**Comment by mikkokar** [comment]
Having tested similar configuration with latest master (at the time of writing 6th November 2019) we need to address the following:

- Each `YamlConfigurationService` must create its own `PathPrefixRouter` that is named after the yaml configuration service. Consider the previous example. The following backend service routers should be created:

  - name: `zone1-router`, type: `PathPrefixRouter` 
  - name: `zone2-router`, type: `PathPrefixRouter` 
  - name: `zone3-router`, type: `PathPrefixRouter` 

These could then be referred from the root HTTP pipeline.

* To make it easy to identify the objects created by a provider, `YamlConfigurationService` needs to tag its created objects with `source=<name>-OriginsFileConverter`. It currently tags them with `source=OriginsFileConverter`, which is not helpful with multiple providers.
