### ISSUE TITLE
Improve StyxObjectStore notification mechanism

### ISSUE THREAD

**Issue by chrisgresty** [HotelsDotCom/styx#525]
The current mechanism is vulnerable to out-of-order notifications, whereby older database states can be emitted after newer ones. Given that it is not essential for all notifications to be emitted, only that the notifications that are emitted are in the correct order, it is possible to replace the queue implementation with one that:
* associates version indices with each new database state
* collapses consecutive notifications
* maintains a limited version history

## Associated test failure
_From Bamboo build [#1140](https://bamboo.hcom/browse/STYX-STYX-1140):_ `StyxObjectStoreTest` - `Compute/Replace an existing value` can result in the watcher being added early to the DB, and so receiving an unexpected early update which fails the test. This test should be re-assessed.

**Comment by mikkokar** [comment]
## Issues
### Out-of-order Notifications

The out-of-order issue affects the initial watch notification in particular. The state change notifications are queued with the modified snapshot. But the initial watch notification is queued as a lambda function that uses the most recent version at the time of its evaluation.

As a result, the initial watch can be followed by other notifications for earlier database snapshots.

### Watchers added too early

Watcher is added to the `watchers` list too early. As a result it might start receiving database change notifications before its initial watch notification.


## Acceptance Criteria

### A snapshot identifier
* Associate a unique identifier for each database snapshot.
* Is an integer (or long).
* Is strictly increasing, starting at zero, and increases by one for each new snapshot.
* A higher identifier implies more recent snapshot.

### Notifications

* Change notifications are collapsed to the most recent snapshot.
* A following "queue invariant" holds true: the notification queue contains at most 1 notification change event.

Suppose there are a burst of modifications to the database, resulting queued notifications for: `[snapshot(n), .. , snapshot(7), snapshot(6)]`, while the database is emitting notifications for `snapshot(5)`. Once the `snapshot(5)` has been processed, the database can skip all intermediate snapshots `6, 7, ...` and emit the most recent snapshot `n`. Therefore there is no need to store more than one watch notification.

* The change notifications and initial watch notifications must preserve their relative order. 

An initial watch notification is sent to a new watch subscriber *only*. Therefore each initial watch notification should be queued as a separate event. The relative ordering among initial watch notifications, and among the database change event must be preserved.

* Initial watch notification should always emit the most recently published snapshot. This is to prevent the initial watch notification from being followed by a database change notification for an earlier snapshot.

**Comment by mikkokar** [comment]
Fixed by: #537
