### ISSUE TITLE
Incorrect origin metrics in routing object mode

### ISSUE THREAD

**Issue by mikkokar** [HotelsDotCom/styx#536]
Origin metric paths are incorrectly constructed when `YamlFileConfigurationService` is used to configure styx from origins file.

The `APP.ORIGIN` hierarchy repeats twice, resulting names like these:

`origins.APP.ORIGIN.APP.ORIGIN.connectionspool.available-connections`

The correct metric path should be:

`origins.APP.ORIGIN.connectionspool.available-connections`

**Comment by bestokes** [comment]
This is resolved.
