### ISSUE TITLE
Please open a Security Advisory

### ISSUE THREAD

**Issue by JLLeitschuh** [HotelsDotCom/styx#568]
Hi Styx Team,

Please open a security advisory and add me so we can discuss the vulnerability.

https://github.com/HotelsDotCom/styx/security/advisories

**Comment by mikkokar** [comment]
Hi @JLLeitschuh. I have opened a draft and added you as a collaborator. Let me know if you can see that?

**Comment by JLLeitschuh** [comment]
I can, thanks! Will disclose shortly
