### ISSUE TITLE
Updates on GHSA-6v7p-v754-j89v?

### ISSUE THREAD

**Issue by JLLeitschuh** [HotelsDotCom/styx#626]
Hey styx team,

Last message before disclosure was that I'd hear back from someone on this:
https://github.com/HotelsDotCom/styx/security/advisories/GHSA-6v7p-v754-j89v

Any updates?

**Comment by JLLeitschuh** [comment]
Also, I updated the severity to 'Moderate' because this attack vector enables XSS and cache poisoning.
Is there any chance you'll have an official versioned release out so that you can update the 'fixed' version to be a publshed version of styx?

**Comment by dvlato** [comment]
Hi @JLLeitschuh , we have a release with the issue fixed now.  I have set the moderity to its previous value and we might have a discussion about that.
I think you should be able to discuss anything else with the Expedia Security Response Team...

**Comment by JLLeitschuh** [comment]
Might want to change the last line of the advisory:

> This vulnerability was found due to this query that I contributed to the Semmle QL project.
> lgtm.com/rules/1510696449842/alerts

Might be better as:

> This vulnerability was found due to this query that [Jonathan Leitschuh](https://twitter.com/jlleitschuh) contributed to the Semmle QL project.
> lgtm.com/rules/1510696449842/alerts
