### ISSUE TITLE
Expose styx provider object database in YAML via admin interface

### ISSUE THREAD

**Issue by chrisgresty** [HotelsDotCom/styx#635]
The Admin interface should display the Provider Object database in a YAML format, in response to a request to `/admin/providers/objects`, similar to the Routing Object database displayed on `/admin/routing/objects'.

The routing object database is not currently displayed as valid YAML - the individual objects are valid, but they are separated by `---` lines. They should be displayed as a valid YAML map or list instead. This should be fixed as part of this Issue, and the new provider object page should be displayed similarly.

**Comment by bestokes** [comment]
Fixed in the above merge.
