### ISSUE TITLE
Rationalise use of plurals in admin URLs

### ISSUE THREAD

**Issue by chrisgresty** [HotelsDotCom/styx#641]
There are plural elements of some URLs in the Admin interface, that do not make sense. Some of these are:
```
/admin/providers/objects  #two plurals in succession
/admin/routing/objects/<objectname>  #"objects" should be singular in this type of URL
```
These should be replaced by:
```
/admin/providers
/admin/provider/<providername>
/admin/provider/objects
/admin/provider/object/<objectname>
/admin/routing/objects
/admin/routing/object/<objectname>
```
- note that the plurals here are used to return a list of resources, not to denote a type of resource.

**Comment by bestokes** [comment]
Fixed in the above merge.
