### ISSUE TITLE
Styx Logging Documentation

### ISSUE THREAD

**Issue by wbautistaEXPEDIA** [HotelsDotCom/styx#85]
Opening this based on advice from @mikkokar 

It would be nice if the logging documentation (_Styx+ + Logging_ page, any other relevant documentation, for that matter) was migrated from the old Hotels.com internal Styx Wiki to GitHub. I have found it quite valuable, and have needed to reference it more than once.

**Comment by kvosper** [comment]
Hi @wbautistaEXPEDIA. The Apache-style logging you are referencing is no longer present in Styx and was removed before it was uploaded to GitHub. We did not use it in Hotels.com as we were not satisfied with its performance. I would advise that if you would like to use this style of logging with Styx, your best option is to develop a plugin for the purpose.

**Comment by kvosper** [comment]
Hi @wbautistaEXPEDIA. The feature you are referencing is no longer present in Styx and was removed before it was uploaded to GitHub. We did not use it in Hotels.com as we were not satisfied with its performance. I would advise that if you would like to use this style of logging with Styx, your best option is to develop a plugin for the purpose.

**Comment by kvosper** [comment]
Please consider using the current HTTP message logging as an alternative, which logs messages with the logger names `com.hotels.styx.http-messages.inbound` and `com.hotels.styx.http-messages.outbound`.

If this does not satisfy your needs, then you could either create a feature request for us, or create your own plugin.

**Comment by wbautistaEXPEDIA** [comment]
👍
