### ISSUE TITLE
Javadocs should be available for viewing online

### ISSUE THREAD

**Issue by kvosper** [HotelsDotCom/styx#9]
# Summary
As a Styx plugin developer, I want to be able to view API documentation for Styx in my browser.

# Description
We have documentation in Javadoc-formatted comments that should be made available online. We need to determine how to generate Javadocs when we make a release, upload them to a suitable location and display them for anyone who wants to view them.

# Acceptable criteria
* Javadocs for *styx-api* module are available at javadoc.io
* Styx Wiki links to the JavaDocs hosted at javadoc.io.

**Comment by massdosage** [comment]
We could possibly create a [GitHub Pages](https://pages.github.com/) site for Styx and put the javadoc and other documentation there.

**Comment by battila7** [comment]
Hi!

Just as an outsider: what about adding Styx to the Central Repository and taking advantage of [javadoc.io](https://javadoc.io)? That solution would satisfy the AC and at the same time Styx would be more approachable being downloadable from the Central Repository.

**Comment by mikkokar** [comment]
Thanks, @battila7, your suggestion. We will look into this.

**Comment by mikkokar** [comment]
I will add a satisfactory javadocs coverage for *styx-api* module. Once ready, we will publish a Styx 1.0 pre-release (or beta) to Maven Central. This makes 1.0 javadocs for *styx-api* available at javadoc.io.

**Comment by mikkokar** [comment]
They appear automatically in javadoc.io. Also we have increased the javadoc coverage for the styx api module.
